### ISSUE TITLE
Support for react-native-web API

### ISSUE THREAD

**Issue by kgoggin** [reasonml-community/bs-react-native#125]
I'm working on building a set of universal components using [react-native-web](https://github.com/necolas/react-native-web). The RNW components' APIs are nearly identical to their react-native counterparts, but there are a few cases where they accept additional web-only props. For instance: many of them support an `accessibilityRole`, which helps inform the library which DOM node to use under the covers and provides `aria-role`. 

What are your thoughts on adding support for these RNW props here so that we can use these bindings for universal components? If you're open to the idea, I'd be happy to help contribute the needed updates.

Thanks!

**Comment by wokalski** [comment]
It's connected to #123. My line of thinking here is that while it should obviously be possible to use RN web with Reason I'm not convinced how we should proceed with this. Multiple little changes in this repo end up being a problem for the vast majority of users - mobile only app devs.

In some places we can provide useful escape hatches (like in #123) however in most, like here, it's much harder. The apis end up being neither mobile nor web compatible. The (unwritten) philosophy behind this library is providing an API which works when compiles. Of course it's just a noble goal, quite impossible to reach but if we can get to 99% of the apis "just working" we did a good job. (it's notably impossible with android/ios specific apis, however maybe we can resolve it, too.)

Alright, praising the status quo is easy but what can we do about it? This is a much harder question. I don't have a better answer than forking this repository. The question is how we will sync changes? It would take some discipline to redirect all upstream-applicable changes to this repo.

Forking this repo is good for rn-web, too. This way, you'll be able to remove native-specific apis. Note that it'll still be possible to build apps with single codebase - BuckleScript supports conditional compilation. There'll just be two separate bsconfigs, one for rn app and one for the web app which will have different dependencies.

Mixing web and mobile in this repo will be a "win" for us - maintainers but will make it much worse for the users.

**Comment by jessep** [comment]
I would also really like to use react native web with reason, create universal components, etc.  @kgoggin Any chance you've hacked together a way of doing this now?

**Comment by jessep** [comment]
@wokalski @kgoggin would it be possible to have an intermediate step wherein we didn't include the rn-web only props but supported the rest of rn-web in the main repo, and thus maintained a universal signature for the components/apis, but let people build universal components from the same library?

**Comment by wokalski** [comment]
@jessep Yes and no. I'm a supporter of supporting both as long it has no impact on RN devs. [This](https://github.com/reasonml-community/bs-react-native/pull/110) and [this](https://github.com/reasonml-community/bs-react-native/pull/123) are good examples of such changes. It is already possible to use reason-react with RN web.

**Comment by ulrikstrid** [comment]
Would it be possible to make a module that extends react-native with the web specific things?

**Comment by wokalski** [comment]
@ulrikstrid I can't think of a good way atm. There exists  the least bad way but I'm not sure which one it is.

**Comment by kgoggin** [comment]
Thanks for the feedback @wokalski. Just so I'm clear: you're saying that the best option as you see it is to create a fork of this repo that adds support for web, and then if you're working in a project that wants to support universal components you'd need to set up a conditional compilation?

I'll offer a disclaimer that I'm pretty new to RN/RNW and Reason development in general so I guess take my opinion with a grain of salt. That said, that solution sounds kind of difficult to manage. The idea of RNW is that you should be able to use a `<Text>` component essentially the same way for any platform without having to think much about it. And, as you said, this is already _almost_ the case with this library, as you can get things more-or-less working with things as they are. I think having to deal with two almost-but-not-quite-the-same libs via a customized build config feels like it goes against what people are trying accomplish with writing universal components in the first place.

Again, this may be to me being a newbie, but I think I'm missing how adding some optional props to the components that are web-specific (and would only get passed in the case where the platform was web) would make the API not work. I can definitely get the argument that expanding the overall API surface adds additional work and complexity to the library and its maintenance, but it sounds like you're saying you feel like the challenge is more technical than organizational? But maybe I'm misunderstanding your point.

@jessep no, I haven't attempted any kind of work-around yet. The project I'm working on is just getting started so we're still kind of evaluating everything.

Thanks for the discussion everyone! Hoping we can work out an agreeable solution to this for all!

**Comment by wokalski** [comment]
It's not a challenge. Adding web only stuff here makes this library worse.

It's because:
1. you need to handle cases you don't care about (for example when you pattern match on a platform and want to have an exhaustive check but this `web` platform you don't use gets in the way and you add an ugly `assert false`)
2. you have props which are web only and then you have props which take no effect on mobile which effectively makes you surprised (this makes the API not work).

It's not build configs conditionals but compile time conditionals.

```
#if WEB
...etc
```

Having a fork is a big organisational challenge but it's better than compromising on quality. Having precise types pays off in the long term.

**Comment by wokalski** [comment]
@MoOx You could have a module called BsReactNative defined in your app and do `include BsReactNativeWeb` for your web target.

**Comment by ulrikstrid** [comment]
I guess someone could create a ReactNativeWithWeb package that includes everything in the correct modules and extends with web specific stuff. That sounds also make it be in sync with this package out of the box.

**Comment by MoOx** [comment]
Like I said, the problem is that components shared across platforms won't compile with web injected props, whatever the trick is. As soon as you use another name (eg: `BsReactNativeWithWeb` or whatever you choose), you will end up having props that won't work on ios or android. And if you use a trick with `BsReactNative` name, you have the opposite problem: it will compile for the web, but not for native (ios/android).

We always had (and will probably always have) props that work in some platform and not other anyway. Lots of examples are android only/ios only props. So even in RN itself, some props don't work on some platforms and that's ok. Why don't we want to do that here as soon as it's documented (prefixed or not)?

**Comment by wokalski** [comment]
I'll let others speak but it's precisely my point. We don't want props that don't work on all platforms. IMO the ultimate goal is to use https://bucklescript.github.io/docs/en/conditional-compilation.

**Comment by MoOx** [comment]
But that's already the case right?
So why don't we continue on the same path until those static if are available in reason (since this bindings use reason). As soon as those became available in reason, ios and android code might be converted as well as web or others?

**Comment by MoOx** [comment]
I would like to reopen this discussion as IRL discussion with friends made me think about this AGAIN. I tried a fork, but it's tedious to maintain as you mostly need to COPY/PASTE/ADJUST/wtf with private/* etc.
Next person that ask for it will have my eternal gratitude, and might trigger me to introduce those props somehow (see ideas above).
Let's discuss this one more time :)

**Comment by Freddy03h** [comment]
Yes ! 👍

It's really annoying to do a JS component each time we want to use an `accessibilityRole` props.
Since RNW becoming popular and used by Twitter PWA, many RN developers (like me) want to create a PWA with RNW using their RN and Reason experience with bs-react-native.

**Comment by kgoggin** [comment]
OP here, and I'd still love to see this happen, FWIW. I've got some hacky work-arounds in place currently (JS component with the props I want, and then I'm writing a custom binding to it in Reason).

One other thing to consider before embarking on this noble quest: besides the component/props issue, there's also the fact that the `Style` module doesn't include some CSS properties that exist on web but not in RN (`outline` comes to mind, but there are a few). A potential solution to this could be to expose some of the underlying API used to construct the functions used to generate styles so that you could implement your own as needed. Of course that's not as nice as just having all the web properties available, but if you were to do that you'd have to figure out how to handle someone using a web property on native.

Thanks for re-opening - I'm hopeful we can figure something out! I've been building an app for the last year that uses shared components for native and web and can attest that it's amazing to be able to share code this way... and when you add Reason on top it's just that much better!

**Comment by wokalski** [comment]
Since there seems to be a big interest in this I'm going to change my stance. I believe we should include RN web here. Now, my question is, can we use https://github.com/janestreet/ppx_optcomp to smoothly add web properties only for the web target? It seems doable!

**Comment by MoOx** [comment]
@wokalski I just took a look to the ppx. I am not sure how are we supposed to define this constants? I would like people to not have to do/import/configure something before using bs-rn.

**Comment by MoOx** [comment]
(Btw, if we are going this, we should handle platform directly like ios/android/web etc... Instead of native/web :) )

**Comment by Freddy03h** [comment]
Yes, it's not native vs web, it's ios vs android vs web.
`Platform.OS === 'web'` and we can use platform-specific files
```
MyComponent.android.js
MyComponent.ios.js
MyComponent.web.js
```

**Comment by wokalski** [comment]
true, it's native/web/android/iOS 😄. Nevertheless the env variable would have to be defined somewhere. I haven't been following `bsb` for a while so I don't know what's the best place to put it.

**Comment by idkjs** [comment]
Non-technically speaking, React-Native is already a thing. BsReactNative is lets do that thing in Reason. So basically, lets do that JS thing in Reason/Ocaml a much more powerful language. In my mind, a core value of this project should be that it can leverage the Ocaml/Reason language to do the JS thing better. So it should be more like, "How would we do that JS thing in RE?" rather than just duplicating the JS. One very important way that could be done is offer the ability to write once, use everywhere. That is, do the thing React Native claims it wants to do but actually do it. If we include this out of the box, you give people reason to come here and use this project right away. Its a serious differentiator. That is I think the motivation of Dart and [Dart for Web](https://webdev.dartlang.org/). Personally, it's a reason that I eagerly anticipate https://github.com/revery-ui/revery which has IOS/Android on its roadmap. https://mobile.twitter.com/bryphe/status/1081236130547159040. 

So lets do the work to make this project shine and do what it can do rather than do what RN did.

**Comment by Freddy03h** [comment]
I think we can start in the platform.re module : https://github.com/reasonml-community/bs-react-native/blob/c6973d3bee4143a3a6ee9690f7ddf80eb1958ecd/src/platform.re

**Comment by wokalski** [comment]
@Freddy03h the thing is that "simply ignored" often means confusion. If we give guarantees that all props are used, it's much smoother experience for the users.

**Comment by Freddy03h** [comment]
@wokalski What is the best exprience you have in mind ? I need to understand, I'm new with Reason, I don't know all the possibilities.

In `MyViewComponent.re` I used `contentInset`, an iOS-only prop, on a `<ScrollView>`.

What should happen at compilation on Android ?

**Comment by MoOx** [comment]
@Freddy03h the idea is to have the compilation for Y that will "skip" props that only works for Y.
So no fail, no error etc. But that involve that you compile your reason to js once per platform. For example `contentInset` props won't even appear in your compiled js for android.

@wokalski I found this last point, since I come from the web (even if I made C in the past haha) a bit inconvenient. I mean having to start a bs watcher per platform... If I work in VSCode (with reason-vscode) and I am developing for both ios & android with the same rn daemon instance, how I am going to handle the compilation "mode" (target?) Same for web/native etc. Seems like extra work on user side.

Btw, something named `onMouseEnter` won't really make sense on ios/android, but that doesn't mean we should "ignore" those at some point. Since bs compile to JS, and that js is... permissive, shouldn't we accept that and just support web as we support ios/android props?

Well for me it seems just more work to do on bs-rn side (as a contributor), and I don't really... _feel_ the value added. Strong types vs "no types" (hello js), here I feel the differences clearly, I can explain it.  But for not accepting props that won't do anything (!= won't "work" like if this could broke something), I don't see the value added because I don't feel it "wrong". As it has been said many times, RN already handle things differently on some platforms, without any "blockers" or explicit things to do (at least in dev mode)... I think the thing that should make it clear where it's working or not is the doc. Nothing more as this bs-rn repo is just a bridge.

**Comment by wokalski** [comment]
I disagree but feel free to do whatever you want. I won’t oppose.

**Comment by Freddy03h** [comment]
I just discovered `accessibilityRole` is supported in react-native since 0.57 😮

**Comment by MoOx** [comment]
`accessibilityRole` "native" values may not be the same as web ones. This will be more tricky if we flag those.
I will try to use `ppx_optcomp` to see if I can use it without pain.

**Comment by ulrikstrid** [comment]
Can we be smart about translations to the web values?
If there is a possible 1-1 mapping it would be nice to add that

**Comment by Freddy03h** [comment]
react-native-web 0.10 introduce support for the new `accessibilityRole` and `accessibilityStates` props : https://github.com/necolas/react-native-web/commit/4040151ee643a02534e72deb51eee76f001b9a5f

web-only props for `accessibilityStates ` are:
- busy
- checked
- expanded
- grabbed
- invalid
- pressed

and for `accessibilityRole`, react-native-web convert them to web aria:
```js
const accessibilityRoleToWebRole = {
  adjustable: 'slider',
  button: 'button',
  header: 'heading',
  image: 'img',
  imagebutton: null,
  keyboardkey: null,
  label: null,
  link: 'link',
  none: 'presentation',
  search: 'search',
  summary: 'region',
  text: null
};
```

**Comment by MoOx** [comment]
@Freddy03h let's continue discussion about this props here 
https://github.com/reasonml-community/bs-react-native/issues/330

**Comment by MoOx** [comment]
We are ok with this, let's make PR when needed. We can try to use optcomp & see where it goes.
