### ISSUE TITLE
Strange runtime error with Animations and top

### ISSUE THREAD

**Issue by gilbert** [reasonml-community/bs-react-native#134]
Here is a repo that isolates the problem: https://github.com/gilbert/rn-reason-bug

I'm attempting to animate a css `top` value. In my code I have something like the following:

```reason
let logoStyle = (offset) => Style.style([
  Style.top( Animated(offset) )
]);
```

However, this causes a very strange runtime error:

    TypeError: Attempted to assign to readonly property.
    ...
    node_modules/react-native/Libraries/Animated/src/nodes/AnimatedValue.js:279:9 in stopTracking
    ...

The `Style.top` is definitely causing it; if you replace it with `Style.top( Pt(200.0) )` instead, then everything is ok (but no animation, obviously).

Is `top` not able to be animated? Thanks.

**Comment by johannth** [comment]
You must use `Animated.View` and `Animated.Text` instead of `View` and `Text` if you want to animate your components. Otherwise you'll get a nice runtime crash.

It would be super nice but probably non-trivial to embed that limitation into the Reason bridge. I.e. somehow make sure you can't use Animated styles on normal View components.

**Comment by wokalski** [comment]
I'm such a moron.

**Comment by johannth** [comment]
You're welcome! I've run into this issue a couple of times so it was fresh in memory. I don't get why you feel like a moron though, haha.
