### ISSUE TITLE
Advocating `open BsReactNative` and exporting generic names like "Types" could be a problem

### ISSUE THREAD

**Issue by MoOx** [reasonml-community/bs-react-native#192]
FYI, I encountered a conflict with a generic name like "Types". Someone on discord told me I should raise the issue but not sure what to offer as an alternative :)

I made an upgrade to 0.5.0 to 0.6.0 and got issue like "Types.myTypes" is not found etc. I struggled a lot but at the end it was a really stupid issue: a conflict with BsReactNative.Types exported module.

Any idea how we could avoid this generic names?

**Comment by MoOx** [comment]
Pretty stupid but I loosed time on trying to add a namespace to my own project to do "MyNamespace.Types" but namespace don't work on their own project... That make me try weird things cause I renamed Types to T after adding a non working namespace (but atom was finding my namespace so it created an another layer of confusion). I simply fixed this by renaming my Types.re to T.re (not great I know).

If you are curious (but again pretty dumb diff at the end) https://github.com/MoOx/moox.io/pull/67

**Comment by blackxored** [comment]
If it'd matter, I second this. For what's basically just `insets` and `touchResponseHandlers`, having `Types` which would conflict with application code, is detrimental IMHO. 

Since the API encourages opening `BsReactNative` and it's quite cumbersome to work with local opens, or to have to type alias anything coming from the user application's `Types` otherwise, I believe that names like `Data`, `Types`, `Utils`, `Helpers` should be prefixed or even better not being a part of the interface at all.

I know this is the price to pay for opening modules, but more often than not this will be a source of errors.

**Comment by wokalski** [comment]
I don't know. I don't use `BsReactNative` rn so I don't have a firm opinion but in general I like the module system precisely because you can have non-confusing generic names without the prefixes.

**Comment by MoOx** [comment]
I guess nobody cares about this :)
