### ISSUE TITLE
BsReactNative.AnimatedRe.calculated

### ISSUE THREAD

**Issue by Rikkiabb** [reasonml-community/bs-react-native#246]
Was updating my project to the latest commit and ran into problems with the new type `AnimatedRe.calculated`. I don't get why the change to `AnimatedRe.calculated` and `AnimatedRe.regular`, since `React native` just worries about if the variable is animated or not?
I would like a way to change a `AnimatedRe.calculated` to `AnimatedRe.regular` or have this as the same type.

**Comment by grabbou** [comment]
Unfortunately, it is not the same type and it's never been. In the past, there used to be `Value.t` and `Interpolation.t`. 

We changed it to use phantom types to better align with Javascript API of React Native. 

Please provide a sample of what cannot be achieved with current API and we will see whether it's our limitation or something that shouldn't be possible due to React Native API.

Here's some old discussion: https://github.com/reasonml-community/bs-react-native/issues/167

**Comment by Rikkiabb** [comment]
Here is an example: 
``` 
Transform.makeAnimated(
  ~translateY=
    AnimatedRe.Value.add(
      state.floatingPageControlTopPosition,
      AnimatedRe.Value.multiply(
        Animated.Value.create(-1.),
        state.verticalScrollViewYPosition,
      ),
    ),
  (),
),
``` 
In this example both `state.floatingPageControlTopPosition` and `state.verticalScrollViewYPosition` are of type `BsReactNative.AnimatedRe.Value.t`.
This was working before the update to animatedRe in bs-react-native. 
The error I get is that it is expecting AnimatedRe.regular but the add function returns Animated.calculated.

**Comment by grabbou** [comment]
Thanks for reporting. We forgot to update the `Transform` module to accept new API. Try using `Transform.makeInterpolated` for now to accept `value(calculated)`.

**Comment by wokalski** [comment]
@Rikkiabb AFAIK, the interface hasn't changed here yet and it's consistent with the behaviour before @grabbou's change. Anyway, if you'd like to contribute, there's an easy fix:
Replace `Animated.Value.t` in `Transform.re` with `Animated.value('a)`. Thanks to that, `Transform.makeAnimated` will accept both interpolated and normal values.
