### ISSUE TITLE
Provide ref prop for all components?

### ISSUE THREAD

**Issue by cknitt** [reasonml-community/bs-react-native#429]
@MoOx @sgny I saw that you added some Android components yesterday. 👍

I noticed that e.g. `ProgressBarAndroid` has a `ref` prop, but there is nothing you can do with a ref once you have obtained it (no functions using that ref are defined).

To keep consistency between components, do we want to

1. add a `ref` prop to all of them or
2. only add `ref` props to components that actually have functions defined that use the ref (like `TextInput.focus`)

?

**Comment by cknitt** [comment]
Might make sense to provide `ref` everywhere to be able to use `setNativeProps`, `measure` etc.

https://facebook.github.io/react-native/docs/direct-manipulation.html

Then we could have something like e.g. for `FlatList`:

```re
type element;
type ref = React.Ref.t(Js.nullable(element));

// Convert FlatList ref to ScrollView ref to call ScrollView methods.
external scrollViewRef: ref => ScrollView.ref = "%identity";

// Convert FlatList ref to Component ref to call Component methods (setNativeProps etc.).
external componentRef: ref => Component.ref = "%identity";
```

**Comment by MoOx** [comment]
IMO we should have `ref` for every component like you explained. We could even make a small stupid automated rule for that =D (just a script that check `type element;\n` is in each `src/components/*.re` files

**Comment by sgny** [comment]
Many components do not have methods defined on `ref`, but I believe we should include it for those which support it. Users will probably find some use for it, especially since `ref` returns _a lot_ of information. 

Some components do not seem to support `ref`s, however. Functional components do not, as already explained in RN documentation, however, something like `DatePickerIOS` does not support it either.

I have noted that `View` is missing the `ref` prop, so I will create a PR for that. I will check which `View` derivatives do not support it, so I will need a little time.

**Comment by cknitt** [comment]
@sgny Please wait, I have already started working on the ref stuff!

**Comment by sgny** [comment]
> @sgny Please wait, I have already started working on the ref stuff!

I haven't started yet, I'll hold off on that then.

**Comment by cknitt** [comment]
Done with #435 and #452.
