### ISSUE TITLE
Expose Style.stringStyle

### ISSUE THREAD

**Issue by grsabreu** [reasonml-community/bs-react-native#91]
In React Native it's a common practice to do `style={{ marginTop: 'auto'}}` so in a flex view an element will "eat" all the remaining space but we can't do this in StyleRe directly with the marginTop as it expects a float.
I think that for now we could do `Style.(style [stringStyle("marginTop", "auto")])`.

If you guys agree on this I can sent the PR for this.

**Comment by wokalski** [comment]
`stringStyle` is an implementation detail and exposing it is not necessary. What's more people can use it to build unsafe APIs which throw in runtime. IMO the best way to solve this particular thing would be using ADTs. So that the api looks like this: `marginTop Auto` or `marginTop (Px 10)` or `marginTop Pct 10`.
